name: CI

on:
  push:
    branches:
      - main
      - lab3
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
          cache: 'pip' # caching pip dependencies
      - run: |
          python3 -m pip install --upgrade pip
          cd app_python && (if [ -f requirements.txt ]; then pip install -r requirements.txt; fi; cd ../../)

      - name: Cache Snyk CLI
        id: cache-snyk-cli
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-snyk-cli-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-snyk-cli-

      - name: Install Snyk CLI
        if: steps.cache-snyk-cli.outputs.cache-hit != 'true'
        run: npm install -g snyk  
      
      - name: Authenticate Snyk
        run: snyk config set api=${{ secrets.SNYK_TOKEN }}
      
      - name: Run Snyk
        run: snyk test --all-projects --severity-threshold=high 

      - name: Linter
        run: |
          pip install flake8
          flake8

      - name: Tests
        run: 
          cd app_python && (python3 -m unittest discover; cd ../../)
      
      - name: Fix Snyk vulnerabilities
        run: snyk wizard --all-projects

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: app_python/
          push: true
          tags: wildqueue/devops-hw:tagname